package guismartcinema;

/**
 *
 * @author laura
 */

import java.util.*;

public class SmartCinemaGUI extends javax.swing.JFrame {

    /**
     * Creates new form SmartCinemaGUI
     */
    public SmartCinemaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ScreenControlPnl = new javax.swing.JPanel();
        ScreenStatusBtn = new javax.swing.JButton();
        ScreenONBtn = new javax.swing.JButton();
        AllScreenOFFBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ScreenResponseTa = new javax.swing.JTextArea();
        ScreenInputTf = new javax.swing.JTextField();
        ScreenInputLbl = new javax.swing.JLabel();
        StaffControlPnl = new javax.swing.JPanel();
        StaffStatusBtn = new javax.swing.JButton();
        StaffHoursBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        StaffResponseTa = new javax.swing.JTextArea();
        StaffInputLbl = new javax.swing.JLabel();
        StaffInputTf = new javax.swing.JTextField();
        DoorControlPnl = new javax.swing.JPanel();
        DoorStatusBtn = new javax.swing.JButton();
        DoorHistoryBtn = new javax.swing.JButton();
        DoorInputLbl = new javax.swing.JLabel();
        DoorInputTf = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        DoorResponseTa = new javax.swing.JTextArea();
        ExitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SmartCinema"));

        ScreenControlPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("ScreenControl"));

        ScreenStatusBtn.setText("ScreenStatus");

        ScreenONBtn.setText("ScreenON");
        ScreenONBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScreenONBtnActionPerformed(evt);
            }
        });

        AllScreenOFFBtn.setText("AllScreenOFF");

        ScreenResponseTa.setColumns(20);
        ScreenResponseTa.setRows(5);
        jScrollPane1.setViewportView(ScreenResponseTa);

        ScreenInputLbl.setText("Input:");

        javax.swing.GroupLayout ScreenControlPnlLayout = new javax.swing.GroupLayout(ScreenControlPnl);
        ScreenControlPnl.setLayout(ScreenControlPnlLayout);
        ScreenControlPnlLayout.setHorizontalGroup(
            ScreenControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScreenControlPnlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ScreenControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScreenStatusBtn)
                    .addComponent(ScreenONBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AllScreenOFFBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(ScreenControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ScreenControlPnlLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(ScreenInputTf))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScreenControlPnlLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(ScreenControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ScreenInputLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        ScreenControlPnlLayout.setVerticalGroup(
            ScreenControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScreenControlPnlLayout.createSequentialGroup()
                .addGroup(ScreenControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ScreenControlPnlLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(ScreenStatusBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScreenONBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AllScreenOFFBtn))
                    .addGroup(ScreenControlPnlLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(ScreenControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ScreenInputTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ScreenInputLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        StaffControlPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("StaffControl"));

        StaffStatusBtn.setText("StaffStatus");

        StaffHoursBtn.setText("StaffHours");

        StaffResponseTa.setColumns(20);
        StaffResponseTa.setRows(5);
        jScrollPane2.setViewportView(StaffResponseTa);

        StaffInputLbl.setText("Input:");

        javax.swing.GroupLayout StaffControlPnlLayout = new javax.swing.GroupLayout(StaffControlPnl);
        StaffControlPnl.setLayout(StaffControlPnlLayout);
        StaffControlPnlLayout.setHorizontalGroup(
            StaffControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StaffControlPnlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(StaffControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StaffHoursBtn)
                    .addComponent(StaffStatusBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(StaffControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StaffControlPnlLayout.createSequentialGroup()
                        .addComponent(StaffInputLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StaffInputTf, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        StaffControlPnlLayout.setVerticalGroup(
            StaffControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StaffControlPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StaffControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StaffControlPnlLayout.createSequentialGroup()
                        .addGroup(StaffControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StaffInputLbl)
                            .addComponent(StaffInputTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StaffControlPnlLayout.createSequentialGroup()
                        .addComponent(StaffStatusBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StaffHoursBtn)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        DoorControlPnl.setBorder(javax.swing.BorderFactory.createTitledBorder("DoorControl"));

        DoorStatusBtn.setText("DoorStatus");

        DoorHistoryBtn.setText("DoorHistory");

        DoorInputLbl.setText("Input:");

        DoorResponseTa.setColumns(20);
        DoorResponseTa.setRows(5);
        jScrollPane3.setViewportView(DoorResponseTa);

        javax.swing.GroupLayout DoorControlPnlLayout = new javax.swing.GroupLayout(DoorControlPnl);
        DoorControlPnl.setLayout(DoorControlPnlLayout);
        DoorControlPnlLayout.setHorizontalGroup(
            DoorControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoorControlPnlLayout.createSequentialGroup()
                .addGroup(DoorControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DoorControlPnlLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(DoorInputLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DoorInputTf))
                    .addGroup(DoorControlPnlLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(DoorControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DoorStatusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DoorHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        DoorControlPnlLayout.setVerticalGroup(
            DoorControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoorControlPnlLayout.createSequentialGroup()
                .addGroup(DoorControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoorInputLbl)
                    .addComponent(DoorInputTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DoorControlPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DoorControlPnlLayout.createSequentialGroup()
                        .addComponent(DoorStatusBtn)
                        .addGap(18, 18, 18)
                        .addComponent(DoorHistoryBtn))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DoorControlPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StaffControlPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScreenControlPnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitBtn)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScreenControlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(StaffControlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DoorControlPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ExitBtn)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void ScreenONBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScreenONBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ScreenONBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartCinemaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartCinemaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartCinemaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartCinemaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartCinemaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllScreenOFFBtn;
    private javax.swing.JPanel DoorControlPnl;
    private javax.swing.JButton DoorHistoryBtn;
    private javax.swing.JLabel DoorInputLbl;
    private javax.swing.JTextField DoorInputTf;
    private javax.swing.JTextArea DoorResponseTa;
    private javax.swing.JButton DoorStatusBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JPanel ScreenControlPnl;
    private javax.swing.JLabel ScreenInputLbl;
    private javax.swing.JTextField ScreenInputTf;
    private javax.swing.JButton ScreenONBtn;
    private javax.swing.JTextArea ScreenResponseTa;
    private javax.swing.JButton ScreenStatusBtn;
    private javax.swing.JPanel StaffControlPnl;
    private javax.swing.JButton StaffHoursBtn;
    private javax.swing.JLabel StaffInputLbl;
    private javax.swing.JTextField StaffInputTf;
    private javax.swing.JTextArea StaffResponseTa;
    private javax.swing.JButton StaffStatusBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
